# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unchained_app', '0005_auto_20180725_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='message',
        ),
    ]
