# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unchained_app', '0008_auto_20180726_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='seller_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sell_offers', to='unchained_app.User'),
            preserve_default=False,
        ),
    ]
