# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unchained_app', '0009_offer_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='seller_id',
        ),
    ]
